# This is a basic workflow to help you get started with Actions

name: Input Testing

on: 
  workflow_dispatch:
    inputs:
      phrase:
        description: 'Phrase to say'
        required: true
        type: string

jobs:
  Running_Script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Replace tokens
        # You may pin to the exact commit or the version.
        # uses: cschleiden/replace-tokens@4f7e3d67f3ff2317ae650842145cdbaefba65189
        uses: cschleiden/replace-tokens@v1.1
        with:
          files: ./output.sh
          
      - name: Run a one-line script
        run: |
          chmod +x ./output.sh
          ./output.sh
        shell: bash
