# This is a basic workflow to help you get started with Actions

name: Input Testing

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          chmod +x ./output.sh
          ./output.sh
        shell: bash
